# Temporary service account since we disabled the subchart and the SA is needed
# by the vault unsealing playbook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: golang-external-secrets
  namespace: golang-external-secrets
